import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Image Uploader App</title>
        <meta name="description" content="Generated by create next app" />
        <link  href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Image Uploader Application
        </h1>
        <div className={styles.cardContainer}>
          <div>
            <h2>
              Upload your image
            </h2>
            <p>File should be .jpeg,Png...</p>
            <div className={styles.innerCard}>
              <Image src="/image.svg" alt=""  height='100px' width='100px'/>
            </div>
            <p>or</p>s
          
          </div>
          <button className={styles.button}>Choose a file</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created By Kundai Clayton
        </a>
      </footer>
    </div>
  )
}

export default Home
